apiVersion: v1
kind: Namespace
metadata:
  name: app-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test-deploy
  namespace: app-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-test
  template:
    metadata:
      labels:
        app: app-test
    spec:
      containers:
        - name: app-test
          image: nginx
          ports:
            - name: web
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-test-svc
  namespace: app-test
  labels:
    app: app-test
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: app-test
---
apiVersion: networking.k8s.io/v1
kind: Ingress
# annotations:
#   cert-manager.io/cluster-issuer: ssl-issuer
metadata:
  name: app-test-ingress
  namespace: app-test
spec:
  rules:
    - host: "app-test.home.aramiske.au"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-test-svc
                port:
                  number: 80
  tls:
    - hosts:
        - app-test.home.aramiske.au
      secretName: app-test-tls-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-test-cert
  namespace: app-test
spec:
  secretName: app-test-tls-secret
  issuerRef:
    name: ssl-issuer
    kind: ClusterIssuer
  dnsNames:
    - app-test.home.aramiske.au

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ssl-issuer
spec:
  selfSigned: {}
